//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenyWPolsce.DatabaseCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CenyWPolsce.DatabaseCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2006&quot;;2,49;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2006&quot;;0,33;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2006&quot;;1,17;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2006&quot;;1,30;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2006 {
            get {
                return ResourceManager.GetString("2006", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2007&quot;;2,78;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2007&quot;;0,34;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2007&quot;;1,27;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2007&quot;;1,48;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2007 {
            get {
                return ResourceManager.GetString("2007", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2008&quot;;3,25;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2008&quot;;0,38;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2008&quot;;1,62;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2008&quot;;1,81;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2008 {
            get {
                return ResourceManager.GetString("2008", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2009&quot;;4,84;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2009&quot;;0,42;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2009&quot;;1,78;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2009&quot;;1,87;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2009 {
            get {
                return ResourceManager.GetString("2009", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2010&quot;;4,73;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2010&quot;;0,40;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2010&quot;;1,79;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2010&quot;;1,68;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2010 {
            get {
                return ResourceManager.GetString("2010", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2011&quot;;3,98;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2011&quot;;0,43;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2011&quot;;2,12;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2011&quot;;2,13;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2011 {
            get {
                return ResourceManager.GetString("2011", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2012&quot;;4,20;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2012&quot;;0,43;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2012&quot;;2,17;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2012&quot;;2,55;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2012 {
            get {
                return ResourceManager.GetString("2012", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2013&quot;;4,35;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2013&quot;;0,42;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2013&quot;;2,25;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2013&quot;;2,65;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2013 {
            get {
                return ResourceManager.GetString("2013", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2014&quot;;3,85;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2014&quot;;0,44;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2014&quot;;2,17;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2014&quot;;2,64;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2014 {
            get {
                return ResourceManager.GetString("2014", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2015&quot;;3,74;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2015&quot;;0,43;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2015&quot;;2,19;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2015&quot;;2,63;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2015 {
            get {
                return ResourceManager.GetString("2015", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2016&quot;;3,85;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2016&quot;;0,41;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2016&quot;;2,03;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2016&quot;;2,64;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2016 {
            get {
                return ResourceManager.GetString("2016", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2017&quot;;3,64;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2017&quot;;0,41;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2017&quot;;2,12;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2017&quot;;2,69;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2017 {
            get {
                return ResourceManager.GetString("2017", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2018&quot;;3,74;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2018&quot;;0,41;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2018&quot;;2,27;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2018&quot;;2,78;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2018 {
            get {
                return ResourceManager.GetString("2018", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;Kod&quot;;&quot;Nazwa&quot;;&quot;Miesiące&quot;;&quot;Rodzaje towarów i usług&quot;;&quot;Cena i wskaźniki&quot;;&quot;Rok&quot;;&quot;Wartosc&quot;;&quot;Jednostka miary&quot;;&quot;Atrybut&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;ryż - za 1kg&quot;;&quot;cena&quot;;&quot;2019&quot;;3,80;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;bułka pszenna - za 50g&quot;;&quot;cena&quot;;&quot;2019&quot;;0,48;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;chleb pszenno-żytni - za 0,5kg&quot;;&quot;cena&quot;;&quot;2019&quot;;2,63;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;mąka pszenna - za 1kg&quot;;&quot;cena&quot;;&quot;2019&quot;;2,89;&quot;zł&quot;;&quot;&quot;;
        ///2200000;&quot;POMORSKIE&quot;;&quot;styczeń&quot;;&quot;kasza jęczmienna - za 0,5kg&quot;;&quot;cena&quot;;&quot; [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _2019 {
            get {
                return ResourceManager.GetString("2019", resourceCulture);
            }
        }
    }
}
